"""Added default profile picture support

Revision ID: 0d2de88d1301
Revises: ee8ec31eeca7
Create Date: 2025-05-14 14:29:46.326411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2de88d1301'
down_revision = 'ee8ec31eeca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dicebar_seed', sa.String(length=50), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('dicebar_seed')

    # ### end Alembic commands ###
