"""empty message

Revision ID: 12d7e9b2089b
Revises: 4872b252a1f2
Create Date: 2025-05-13 13:00:14.633434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d7e9b2089b'
down_revision = '4872b252a1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purchased_items_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglists', schema=None) as batch_op:
        batch_op.drop_column('purchased_items_count')
        batch_op.drop_column('items_count')

    # ### end Alembic commands ###
