"""Added date of creation to households

Revision ID: 4872b252a1f2
Revises: 5e62616c943c
Create Date: 2025-05-12 01:20:12.173902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4872b252a1f2'
down_revision = '5e62616c943c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
