"""Added support for custom img paths for users

Revision ID: 535f53e22245
Revises: 0d2de88d1301
Create Date: 2025-05-14 18:20:53.501192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535f53e22245'
down_revision = '0d2de88d1301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_filename', sa.String(length=128), nullable=True))
        batch_op.drop_column('custom_image_path')
        batch_op.drop_column('dicebar_seed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dicebar_seed', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('custom_image_path', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('avatar_filename')

    # ### end Alembic commands ###
