"""Bug Fixes

Revision ID: 8b54da8b8c5d
Revises: cc0ce3719d07
Create Date: 2025-05-14 19:19:54.111376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b54da8b8c5d'
down_revision = 'cc0ce3719d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=256), nullable=True))
        batch_op.drop_column('avatar_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
