"""Added support for custom img paths for users

Revision ID: ee8ec31eeca7
Revises: 12d7e9b2089b
Create Date: 2025-05-14 14:24:12.114195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8ec31eeca7'
down_revision = '12d7e9b2089b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_image_path', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('custom_image_path')

    # ### end Alembic commands ###
